name: Arcticor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0014ab'
    - '#f9fce7'
    - '#a3bbbf'
    - '#616d19'
    - '#4b88ce'
  brandStrength: 0.21554216998629272
  lightness: 0.053171205800026655
  saturation: 0.5633280233014375
  rhythmicContrast: 0.7458881686907262
purpose: []
